# Change these first
owner: jamiew0w
repo: status.honk.ie

# Add your sites here
sites:
  - name: honk.ie
    url: https://honk.ie
  - name: plex.honk.ie
    url: https://plex.honk.ie/web/index.html
  - name: ombi.honk.ie
    url: https://ombi.honk.ie
  - name: tautulli.honk.ie
    url: https://tautulli.honk.ie/auth/login?redirect_uri=/

assignees:
  - jamiew0w

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.honk.ie
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.honk.ie
  
i18n:
  footer: This page is [open source]($REPO).

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 1 * * *"
  summary: "*/5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
