# Change these first
owner: jamiew0w
repo: status.honk.ie
  
# Add your sites here
sites:
  - name: honk.ie
    url: https://honk.ie
    icon: https://honk.ie/plugins/images/faviconCustom/favicon.ico
  - name: plex.honk.ie
    url: https://plex.honk.ie/web/index.html
    icon: https://plex.honk.ie/web/favicon.ico
  - name: ombi.honk.ie
    url: https://ombi.honk.ie
    icon: https://ombi.honk.ie/images/favicon/favicon.ico
  - name: tautulli.honk.ie
    url: https://tautulli.honk.ie/auth/login?redirect_uri=/

assignees:
  - jamiew0w

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.honk.ie
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.honk.ie
  theme: "ocean"

i18n:
  footer: <a href="https://honk.ie" target="_blank">honk.ie</a>

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 1 * * *"
  summary: "*/5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
